
CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

koordinatenSystem: koordinatenSystem.c libSVG.h
	$(CC) $(CFLAGS) -o koordinatenSystem koordinatenSystem.c 

run: koordinatenSystem
	./koordinatenSystem
